In [2]:
import numpy as np
from numpy.random import randn


Reducing the decimal place of the random numbers to 2

In [3]:
np.set_printoptions(precision=2)

Creating arrays and Matrixes

In [6]:
a = np.array([1,2,3,4,5,6])
a

m = np.array([[10,20,30],[40,50,60]])
m

array([[10, 20, 30],
       [40, 50, 60]])

Creating an array via assignment

In [10]:
# Generating random numbers and assigning them to an array
np.random.seed(25)
c= 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

Creating an array of sequential numbers from 1-34

In [11]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

Performing basic arithmetic on arrays

In [12]:
a*10

array([10, 20, 30, 40, 50, 60])

In [13]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [14]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

Multiply basic matrixes and linear algebra

In [16]:
np.set_printoptions(precision=2)


aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])

aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [17]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])

bb


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [18]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

Matrix multiplication using numpy

In [19]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

Using descriptive statistics

In [20]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import scipy
from scipy import stats

In [22]:
address = "C:/Users/HP/Documents/Programming/PROJECTS/Exercise Files/Data/mtcars.csv"

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb']

cars.head()

car_names   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2

[5 rows x 12 columns]

Using the sum function calculates the sum of all the values in each column

In [23]:
cars.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

Calculating the sum of the values in the rows

In [28]:
new_df = cars.drop(columns='car_names')
new_df.head()

new_df.sum(axis=1)


0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

In [30]:
new_df.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [31]:
new_df.max()

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

Identify the index of the row where the max value is located

In [32]:
mpg = cars.mpg
mpg.idxmax()

19