In [1]:
import numpy as np
from numpy.random import randn


Reducing the decimal place of the random numbers to 2

In [2]:
np.set_printoptions(precision=2)

Creating arrays and Matrixes

In [3]:
a = np.array([1,2,3,4,5,6])
a

m = np.array([[10,20,30],[40,50,60]])
m

array([[10, 20, 30],
       [40, 50, 60]])

Creating an array via assignment

In [4]:
# Generating random numbers and assigning them to an array
np.random.seed(25)
c= 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

Creating an array of sequential numbers from 1-34

In [5]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

Performing basic arithmetic on arrays

In [6]:
a*10

array([10, 20, 30, 40, 50, 60])

In [7]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [8]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

Multiply basic matrixes and linear algebra

In [9]:
np.set_printoptions(precision=2)


aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])

aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [10]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])

bb


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

Matrix multiplication using numpy

In [12]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

Using descriptive statistics

In [13]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import scipy
from scipy import stats

C:\Users\HP\AppData\Local\Temp\ipykernel_16776\1716275390.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [14]:
address = "C:/Users/HP/Documents/Programming/PROJECTS/Exercise Files/Data/mtcars.csv"

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb']

cars.head()

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

Using the sum function calculates the sum of all the values in each column

In [15]:
cars.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

Calculating the sum of the values in the rows

In [16]:
new_df = cars.drop(columns='car_names')
new_df.head()

new_df.sum(axis=1)


0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

In [17]:
new_df.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [18]:
new_df.max()

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

Identify the index of the row where the max value is located

In [19]:
mpg = cars.mpg
mpg.idxmax()

19

In [21]:
address = "C:/Users/HP/Documents/Programming/PROJECTS/Exercise Files/Data/mtcars.csv"

cars = pd.read_csv(address)
cars.columns = ['car_names','mpg','cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb']

cars.index = cars.car_names
cars.head(15)

car_names   mpg  cyl   disp   hp  drat     wt  \
car_names                                                                    
Mazda RX4                    Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag            Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                  Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive          Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   
Valiant                        Valiant  18.1    6  225.0  105  2.76  3.460   
Duster 360                  Duster 360  14.3    8  360.0  245  3.21  3.570   
Merc 240D                    Merc 240D  24.4    4  146.7   62  3.69  3.190   
Merc 230                      Merc 230  22.8    4  140.8   95  3.92  3.150   
Merc 280                      Merc 280  19.2    6  167.6  123  3.92  3.440   
Merc 280C                    Merc 280C  17.8    6  167.6  123  3.92  3.440   
Merc 450SE                  Merc 450SE  16.4    8  275.8  180  3.07  4.070   
Merc 450SL                  Merc 450SL  17.3    8  275.8  180  3.07  3.730   
Merc 450SLC                Merc 450SLC  15.2    8  275.8  180  3.07  3.780   
Cadillac Fleetwood  Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250   

                     qsec  vs  am  gear  carb  
car_names                                      
Mazda RX4           16.46   0   1     4     4  
Mazda RX4 Wag       17.02   0   1     4     4  
Datsun 710          18.61   1   1     4     1  
Hornet 4 Drive      19.44   1   0     3     1  
Hornet Sportabout   17.02   0   0     3     2  
Valiant             20.22   1   0     3     1  
Duster 360          15.84   0   0     3     4  
Merc 240D           20.00   1   0     4     2  
Merc 230            22.90   1   0     4     2  
Merc 280            18.30   1   0     4     4  
Merc 280C           18.90   1   0     4     4  
Merc 450SE          17.40   0   0     3     3  
Merc 450SL          17.60   0   0     3     3  
Merc 450SLC         18.00   0   0     3     3  
Cadillac Fleetwood  17.98   0   0     3     4

Counting the number of unique values in an array of series object.

In [22]:
carb = cars.carb

carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

Creating a sub group

In [23]:
cars_cat = cars[['cyl','vs','am','gear','carb']]
cars_cat.head()


cyl  vs  am  gear  carb
car_names                                 
Mazda RX4            6   0   1     4     4
Mazda RX4 Wag        6   0   1     4     4
Datsun 710           4   1   1     4     1
Hornet 4 Drive       6   1   0     3     1
Hornet Sportabout    8   0   0     3     2

Grouping a dataframe by values in a particular column

In [24]:
gear_group = cars_cat.groupby('gear')
gear_group.describe()

cyl                                                 vs            ...  \
     count      mean       std  min  25%  50%  75%  max count      mean  ...   
gear                                                                     ...   
3     15.0  7.466667  1.187234  4.0  8.0  8.0  8.0  8.0  15.0  0.200000  ...   
4     12.0  4.666667  0.984732  4.0  4.0  4.0  6.0  6.0  12.0  0.833333  ...   
5      5.0  6.000000  2.000000  4.0  4.0  6.0  8.0  8.0   5.0  0.200000  ...   

       am       carb                                               
      75%  max count      mean       std  min  25%  50%  75%  max  
gear                                                               
3     0.0  0.0  15.0  2.666667  1.175139  1.0  2.0  3.0  4.0  4.0  
4     1.0  1.0  12.0  2.333333  1.302678  1.0  1.0  2.0  4.0  4.0  
5     1.0  1.0   5.0  4.400000  2.607681  2.0  2.0  4.0  6.0  8.0  

[3 rows x 32 columns]

Transforming variable to categorical data type